"""
Career Taxonomy - 15+ Categories with Regex Rules - Phase 1.

ponytail: Ordered regex matching. First match wins.
Categories cover Peru/Latam tech job market specifically.
"""

from typing import NamedTuple


class CareerCategory(NamedTuple):
    """A career category with its display name and ordered regex patterns."""

    id: str  # URL-safe identifier
    name: str  # Display name
    patterns: list[str]  # Ordered regex patterns (first match wins)
    keywords: list[str]  # Additional keywords for hybrid matching


# Ordered list - most specific first to avoid false positives
# ponytail: Order matters! More specific patterns MUST come before generic ones.
CAREER_CATEGORIES: list[CareerCategory] = [
    CareerCategory(
        id="ciencia-datos-ia",
        name="Ciencia de Datos e IA",
        patterns=[
            r"\bdata scientist\b",
            r"\bcient[íi]fico de datos\b",
            r"\bdata engineer\b",
            r"\bmachine learning\b",
            r"\bml engineer\b",
            r"\bdeep learning\b",
            r"\binteligencia artificial\b",
            r"\bia\b.*\bcient[íi]fico\b",
            r"\bai engineer\b",
            r"\banalytics engineer\b",
            r"\bdata analyst\b.*\bsenior\b",
            r"\bbig data\b",
            r"\bdata architect\b",
            r"\bbi analyst\b",
            r"\bbusiness intelligence\b",
        ],
        keywords=["python", "sql", "tensorflow", "pytorch", "spark", "airflow", "dbt"],
    ),
    CareerCategory(
        id="desarrollo-backend",
        name="Desarrollo Backend",
        patterns=[
            r"\bbackend\b",
            r"\bback[- ]end\b",
            r"\bback end\b",
            r"\bapi\b.*\bdeveloper\b",
            r"\bdeveloper\b.*\bapi\b",
            r"\bserver\b.*\bdeveloper\b",
            r"\bnode\b",
            r"\bjava\b",
            r"\bspring\b",
            r"\b.net\b",
            r"\bc#\b",
            r"\bgolang\b",
            r"\bgo\b",
            r"\brust\b",
            r"\bphp\b",
            r"\blaravel\b",
            r"\bdjango\b",
            r"\bflask\b",
            r"\bfastapi\b",
            r"\bexpress\b",
            r"\bnestjs\b",
        ],
        keywords=[
            "python",
            "java",
            "node",
            "sql",
            "postgresql",
            "mongodb",
            "redis",
            "docker",
            "django",
            "flask",
            "fastapi",
            "spring",
            "laravel",
        ],
    ),
    CareerCategory(
        id="desarrollo-frontend",
        name="Desarrollo Frontend",
        patterns=[
            r"\bfrontend\b",
            r"\bfront[- ]end\b",
            r"\bfront end\b",
            r"\bui developer\b",
            r"\buix\b",
            r"\bweb developer\b",
            r"\breact\b",
            r"\bangular\b",
            r"\bvue\b",
            r"\bsvelte\b",
            r"\bnextjs\b",
            r"\bnext\.js\b",
            r"\breactjs\b",
            r"\bjavascript\b",
            r"\btypescript\b",
            r"\btailwind\b",
            r"\bscss\b",
            r"\bcss\b",
            r"\bhtml\b",
            r"\bwebflow\b",
        ],
        keywords=["react", "angular", "vue", "javascript", "typescript", "html", "css"],
    ),
    CareerCategory(
        id="desarrollo-fullstack",
        name="Desarrollo Fullstack",
        patterns=[
            r"\bfullstack\b",
            r"\bfull[- ]stack\b",
            r"\bfull stack\b",
            r"\bfull[- ]stack\b.*\bdeveloper\b",
            r"\bdeveloper\b.*\bfull[- ]stack\b",
        ],
        keywords=["react", "node", "python", "postgresql", "typescript"],
    ),
    CareerCategory(
        id="desarrollo-mobile",
        name="Desarrollo Mobile",
        patterns=[
            r"\bmobile\b",
            r"\bapp\b.*\bdeveloper\b",
            r"\bdeveloper\b.*\bapp\b",
            r"\bandroid\b",
            r"\bios\b",
            r"\bswift\b",
            r"\bkotlin\b",
            r"\bflutter\b",
            r"\breact native\b",
            r"\bxamarin\b",
            r"\binfoSistemas\b",
            r"\bapps\b",
            r"\bmóviles\b",
        ],
        keywords=["swift", "kotlin", "flutter", "react native", "android", "ios"],
    ),
    CareerCategory(
        id="devops-cloud",
        name="DevOps y Cloud",
        patterns=[
            r"\bdevops\b",
            r"\bsre\b",
            r"\bsite reliability\b",
            r"\bcloud\b",
            r"\baws\b",
            r"\bazure\b",
            r"\bgcp\b",
            r"\bgoogle cloud\b",
            r"\bsystems engineer\b",
            r"\binfrastructure\b",
            r"\bterraform\b",
            r"\bkubernetes\b",
            r"\bk8s\b",
            r"\bdocker\b",
            r"\bci/cd\b",
            r"\bjenkins\b",
            r"\bgithub actions\b",
            r"\bansible\b",
            r"\bpuppet\b",
            r"\bchef\b",
            r"\bcloud engineer\b",
            r"\bplatform engineer\b",
        ],
        keywords=["aws", "azure", "gcp", "terraform", "kubernetes", "docker", "linux"],
    ),
    CareerCategory(
        id="qa-testing",
        name="QA y Testing",
        patterns=[
            r"\bqa\b",
            r"\bq[ao] engineer\b",
            r"\bquality assurance\b",
            r"\btester\b",
            r"\btesting\b",
            r"\bautomation\b.*\btest\b",
            r"\btest\b.*\bautomation\b",
            r"\bselenium\b",
            r"\bcypress\b",
            r"\bplaywright\b",
            r"\btest automation\b",
            r"\bmanual tester\b",
            r"\bperformance test\b",
            r"\bload test\b",
        ],
        keywords=["selenium", "cypress", "playwright", "jest", "python", "sql"],
    ),
    CareerCategory(
        id="seguridad-informatica",
        name="Seguridad Informática",
        patterns=[
            r"\bsecurity\b",
            r"\bcybersecurity\b",
            r"\bseguridad\b",
            r"\bpenetration\b",
            r"\bpentest\b",
            r"\bhacker\b",
            r"\bethical hacker\b",
            r"\binfosec\b",
            r"\bsecurity engineer\b",
            r"\bsecurity analyst\b",
            r"\bcia\b",
            r"\bfirewall\b",
            r"\bsoc\b",
            r"\bsiempython\b",
            r"\bcriptografía\b",
            r"\bcryptography\b",
        ],
        keywords=["python", "linux", "networking", "firewall", "SIEM"],
    ),
    CareerCategory(
        id="ingenieria-datos",
        name="Ingeniería de Datos",
        patterns=[
            r"\bdata engineer\b",
            r"\bingeniero\b.*\bdatos\b",
            r"\betl\b",
            r"\bdata pipeline\b",
            r"\bspark\b",
            r"\bhadoop\b",
            r"\bkafka\b",
            r"\bairflow\b",
            r"\bdbt\b",
            r"\bdata warehouse\b",
            r"\blakehouse\b",
            r"\bsnowflake\b",
            r"\bdatabricks\b",
            r"\bbig query\b",
        ],
        keywords=["python", "sql", "spark", "airflow", "kafka", "snowflake"],
    ),
    CareerCategory(
        id="product-manager",
        name="Product Manager",
        patterns=[
            r"\bproduct manager\b",
            r"\bpm\b",
            r"\bproduct owner\b",
            r"\bproduct lead\b",
            r"\bproduct director\b",
            r"\bgerente\b.*\bproducto\b",
            r"\bproduct strategy\b",
            r"\bproduct discovery\b",
        ],
        keywords=["agile", "scrum", "jira", "analytics", "sql"],
    ),
    CareerCategory(
        id="ux-ui-design",
        name="Diseño UX/UI",
        patterns=[
            r"\bux\b",
            r"\bui\b.*\bdesigner\b",
            r"\buser experience\b",
            r"\buser interface\b",
            r"\binteraction design\b",
            r"\bvisual design\b",
            r"\bproduct design\b",
            r"\bui/ux\b",
            r"\bux/ui\b",
            r"\bfigma\b",
            r"\bdesigner\b.*\bproduct\b",
        ],
        keywords=["figma", "sketch", "adobe", "prototyping", "user research"],
    ),
    CareerCategory(
        id="analista-negocios",
        name="Analista de Negocios TI",
        patterns=[
            r"\banalista\b",
            r"\banalyst\b",
            r"\bbusiness analyst\b",
            r"\bfunctional analyst\b",
            r"\bsystems analyst\b",
            r"\btechnical analyst\b",
            r"\banalista\b.*\bsistemas\b",
            r"\banalista\b.*\bnegocios\b",
            r"\banalista\b.*\bfUNCIONAL\b",
        ],
        keywords=["sql", "excel", "jira", "process modeling", "requirements"],
    ),
    CareerCategory(
        id="gestion-proyectos",
        name="Gestión de Proyectos TI",
        patterns=[
            r"\bproject manager\b",
            r"\bpm\b",
            r"\bprogram manager\b",
            r"\bportfolio manager\b",
            r"\bproject lead\b",
            r"\bproject director\b",
            r"\bgerente\b.*\bproyecto\b",
            r"\bpmp\b",
            r"\bscrum master\b",
            r"\bscrum master\b",
            r"\b Agile Coach\b",
        ],
        keywords=["agile", "scrum", "jira", "ms project", "prince2"],
    ),
    CareerCategory(
        id="infraestructura-sistemas",
        name="Infraestructura y Sistemas",
        patterns=[
            r"\bsysadmin\b",
            r"\bsystems admin\b",
            r"\bsystem administrator\b",
            r"\binfrastructure\b",
            r"\bserver\b",
            r"\bnetwork engineer\b",
            r"\bnetwork admin\b",
            r"\blinux\b",
            r"\bwindows server\b",
            r"\bvmware\b",
            r"\bhyper-v\b",
            r"\bvirtualization\b",
            r"\bIT operations\b",
            r"\btech support\b",
            r"\bsoporte\b.*\btécnico\b",
            r"\bsoporte\b.*\bti\b",
            r"\basistencia\b.*\btécnica\b",
        ],
        keywords=["linux", "windows server", "networking", "vmware", "powershell"],
    ),
    CareerCategory(
        id="datos-business-intelligence",
        name="Datos y Business Intelligence",
        patterns=[
            r"\bbi\b",
            r"\bbusiness intelligence\b",
            r"\bpower bi\b",
            r"\btableau\b",
            r"\blooker\b",
            r"\bqlik\b",
            r"\bsap\b",
            r"\bdata visualization\b",
            r"\breporting analyst\b",
            r"\bbi analyst\b",
            r"\bdata analyst\b",
        ],
        keywords=["sql", "tableau", "power bi", "excel", "python"],
    ),
    CareerCategory(
        id="desarrollo-software-general",
        name="Desarrollo de Software General",
        patterns=[
            r"\bsoftware engineer\b",
            r"\bsoftware developer\b",
            r"\bdeveloper\b",
            r"\bprogrammer\b",
            r"\barchitect\b",
            r"\bsoftware architect\b",
            r"\btech lead\b",
            r"\bsenior developer\b",
            r"\bjunior developer\b",
            r"\bmid developer\b",
            r"\bdesarrollador\b",
            r"\bprogramador\b",
            r"\bingeniero\b.*\bsoftware\b",
        ],
        keywords=["python", "java", "javascript", "sql", "git"],
    ),
    CareerCategory(
        id="game-dev",
        name="Desarrollo de Videojuegos",
        patterns=[
            r"\bgame\b",
            r"\bvideojuego\b",
            r"\bgame developer\b",
            r"\bgame designer\b",
            r"\bunity\b",
            r"\bunreal\b",
            r"\b3d\b",
            r"\bgameplay\b",
            r"\bgamedev\b",
            r"\bmotion\b",
        ],
        keywords=["unity", "unreal", "c++", "c#"],
    ),
    CareerCategory(
        id="gestion-bases-datos",
        name="Gestión de Bases de Datos",
        patterns=[
            r"\bdba\b",
            r"\bdatabase\b.*\badministrator\b",
            r"\bdatabase engineer\b",
            r"\bsql\b",
            r"\bpostgresql\b",
            r"\bmysql\b",
            r"\boracle\b",
            r"\bsql server\b",
            r"\bmongodb\b",
            r"\bnosql\b",
            r"\bdata modeling\b",
            r"\bdatabase architect\b",
        ],
        keywords=["sql", "postgresql", "mysql", "oracle", "mongodb"],
    ),
]


# Fast lookup dict by ID
CATEGORY_BY_ID: dict[str, CareerCategory] = {c.id: c for c in CAREER_CATEGORIES}

# Fast lookup dict by name (case-insensitive)
CATEGORY_BY_NAME: dict[str, CareerCategory] = {
    c.name.lower(): c for c in CAREER_CATEGORIES
}

# List of all category IDs
ALL_CATEGORY_IDS: list[str] = [c.id for c in CAREER_CATEGORIES]

# List of all category names
ALL_CATEGORY_NAMES: list[str] = [c.name for c in CAREER_CATEGORIES]


__all__ = [
    "CareerCategory",
    "CAREER_CATEGORIES",
    "CATEGORY_BY_ID",
    "CATEGORY_BY_NAME",
    "ALL_CATEGORY_IDS",
    "ALL_CATEGORY_NAMES",
]
