"""
Seed script for learning_paths collection.
Run once to populate MongoDB with the 5 academic goal paths.

Usage:
    python -m app.core.seed_learning_paths
"""

from datetime import datetime
from app.core.database import connect_to_mongo, get_database, close_mongo_connection


SEED_DATA = [
    # ═══════════════════════════════════════════════════════════════
    # BACKEND
    # ═══════════════════════════════════════════════════════════════
    {
        "goal_id": "Backend",
        "title": "Ruta Desarrollo Backend",
        "subtitle": "Domina el desarrollo del lado del servidor",
        "color": "#6366f1",
        "nodes": [
            {
                "id": "fundamentos-programacion",
                "name": "Fundamentos de Programación",
                "description": "Variables, tipos de datos, control de flujo, funciones y estructuras básicas",
                "difficulty": "basic",
                "estimated_weeks": 3,
                "status": "planned",
                "icon": "bi-code",
                "order": 0,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - Python",
                        "url": "https://www.freecodecamp.org/learn/python-for-beginners/",
                        "is_free": True,
                        "description": "Curso gratuito de Python desde cero",
                    },
                    {
                        "type": "practice",
                        "name": "Exercism - Python Track",
                        "url": "https://exercism.org/tracks/python",
                        "is_free": True,
                        "description": "Ejercicios prácticos con mentores",
                    },
                    {
                        "type": "article",
                        "name": "Python.org Tutorial",
                        "url": "https://docs.python.org/3/tutorial/",
                        "is_free": True,
                        "description": "Tutorial oficial de Python",
                    },
                ],
            },
            {
                "id": "estructuras-datos",
                "name": "Estructuras de Datos",
                "description": "Arrays, listas enlazadas, pilas, colas, árboles, grafos y hashing",
                "difficulty": "intermediate",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-diagram-3",
                "order": 1,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - Data Structures",
                        "url": "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
                        "is_free": True,
                        "description": "Estructuras de datos en JavaScript",
                    },
                    {
                        "type": "practice",
                        "name": "Visualgo",
                        "url": "https://visualgo.net/",
                        "is_free": True,
                        "description": "Visualización interactiva de algoritmos",
                    },
                    {
                        "type": "article",
                        "name": "GeeksforGeeks - DS",
                        "url": "https://www.geeksforgeeks.org/data-structures/",
                        "is_free": True,
                        "description": "Artículos completos sobre estructuras de datos",
                    },
                ],
            },
            {
                "id": "algoritmos",
                "name": "Algoritmos Avanzados",
                "description": "Ordenamiento, búsqueda, recursión, programación dinámica",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-brain",
                "order": 2,
                "resources": [
                    {
                        "type": "course",
                        "name": "Khan Academy - Algorithms",
                        "url": "https://www.khanacademy.org/computing/computer-science/algorithms",
                        "is_free": True,
                        "description": "Fundamentos de algoritmos",
                    },
                    {
                        "type": "practice",
                        "name": "LeetCode",
                        "url": "https://leetcode.com/",
                        "is_free": True,
                        "description": "Problemas de algoritmos para entrevistas",
                    },
                    {
                        "type": "book",
                        "name": "Introduction to Algorithms (CLRS)",
                        "url": "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/",
                        "is_free": False,
                        "description": "El libro de referencia en algoritmos",
                    },
                ],
            },
            {
                "id": "bases-datos",
                "name": "Bases de Datos",
                "description": "SQL, PostgreSQL, MongoDB, diseño relacional y ORM",
                "difficulty": "intermediate",
                "estimated_weeks": 3,
                "status": "planned",
                "icon": "bi-database",
                "order": 3,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - SQL",
                        "url": "https://www.freecodecamp.org/learn/relational-database/",
                        "is_free": True,
                        "description": "Curso de bases de datos relacionales",
                    },
                    {
                        "type": "tool",
                        "name": "PostgreSQL Tutorial",
                        "url": "https://www.postgresqltutorial.com/",
                        "is_free": True,
                        "description": "Tutorial completo de PostgreSQL",
                    },
                    {
                        "type": "article",
                        "name": "MongoDB University",
                        "url": "https://university.mongodb.com/",
                        "is_free": True,
                        "description": "Cursos oficiales de MongoDB",
                    },
                ],
            },
            {
                "id": "apis-rest",
                "name": "APIs RESTful",
                "description": "Diseño REST, autenticación, documentación, versionado",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-cloud-arrow-up",
                "order": 4,
                "resources": [
                    {
                        "type": "article",
                        "name": "RESTful API Design - Microsoft",
                        "url": "https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design",
                        "is_free": True,
                        "description": "Guías de Microsoft para APIs REST",
                    },
                    {
                        "type": "tool",
                        "name": "Postman Learning Center",
                        "url": "https://learning.postman.com/",
                        "is_free": True,
                        "description": "Aprende a probar y documentar APIs",
                    },
                    {
                        "type": "practice",
                        "name": "JSONPlaceholder",
                        "url": "https://jsonplaceholder.typicode.com/",
                        "is_free": True,
                        "description": "API fake para practicar",
                    },
                ],
            },
            {
                "id": "frameworks-backend",
                "name": "Frameworks Backend",
                "description": "Node.js/Express, FastAPI, Django - construcción de APIs completas",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-box-seam",
                "order": 5,
                "resources": [
                    {
                        "type": "course",
                        "name": "FastAPI Official Tutorial",
                        "url": "https://fastapi.tiangolo.com/tutorial/",
                        "is_free": True,
                        "description": "Tutorial oficial de FastAPI",
                    },
                    {
                        "type": "course",
                        "name": "Node.js Official Guides",
                        "url": "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
                        "is_free": True,
                        "description": "Guías oficiales de Node.js",
                    },
                    {
                        "type": "article",
                        "name": "Django Documentation",
                        "url": "https://docs.djangoproject.com/",
                        "is_free": True,
                        "description": "Documentación oficial de Django",
                    },
                ],
            },
            {
                "id": "devops-basico",
                "name": "DevOps Básico",
                "description": "Docker, Git avanzado, CI/CD, Linux fundamentals",
                "difficulty": "intermediate",
                "estimated_weeks": 3,
                "status": "planned",
                "icon": "bi-git",
                "order": 6,
                "resources": [
                    {
                        "type": "course",
                        "name": "Docker Official Tutorial",
                        "url": "https://docs.docker.com/get-started/",
                        "is_free": True,
                        "description": "Tutorial oficial de Docker",
                    },
                    {
                        "type": "article",
                        "name": "Linux Journey",
                        "url": "https://linuxjourney.com/",
                        "is_free": True,
                        "description": "Aprende Linux desde cero",
                    },
                    {
                        "type": "tool",
                        "name": "GitHub Actions Docs",
                        "url": "https://docs.github.com/en/actions",
                        "is_free": True,
                        "description": "Documentación de CI/CD con GitHub Actions",
                    },
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════
    # AI / CIENCIA DE DATOS
    # ═══════════════════════════════════════════════════════════════
    {
        "goal_id": "AI",
        "title": "Ruta Ciencia de Datos e IA",
        "subtitle": "Domina la inteligencia artificial y machine learning",
        "color": "#8b5cf6",
        "nodes": [
            {
                "id": "python-datos",
                "name": "Python para Datos",
                "description": "Sintaxis Python, Pandas, NumPy, Jupyter notebooks",
                "difficulty": "basic",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-filetype-py",
                "order": 0,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - Python",
                        "url": "https://www.freecodecamp.org/learn/python-for-beginners/",
                        "is_free": True,
                        "description": "Python desde cero",
                    },
                    {
                        "type": "course",
                        "name": "Kaggle - Python",
                        "url": "https://www.kaggle.com/learn/python",
                        "is_free": True,
                        "description": "Curso de Python para ciencia de datos",
                    },
                    {
                        "type": "tool",
                        "name": "Google Colab",
                        "url": "https://colab.research.google.com/",
                        "is_free": True,
                        "description": "Jupyter notebooks en la nube gratis",
                    },
                ],
            },
            {
                "id": "matematicas-ia",
                "name": "Matemáticas para IA",
                "description": "Álgebra lineal, probabilidad, estadística, cálculo",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-calculator",
                "order": 1,
                "resources": [
                    {
                        "type": "course",
                        "name": "Khan Academy - Linear Algebra",
                        "url": "https://www.khanacademy.org/math/linear-algebra",
                        "is_free": True,
                        "description": "Álgebra lineal interactiva",
                    },
                    {
                        "type": "course",
                        "name": "Khan Academy - Statistics",
                        "url": "https://www.khanacademy.org/math/statistics-probability",
                        "is_free": True,
                        "description": "Probabilidad y estadística",
                    },
                    {
                        "type": "article",
                        "name": "3Blue1Brown - Essence of Linear Algebra",
                        "url": "https://www.3blue1brown.com/topics/linear-algebra",
                        "is_free": True,
                        "description": "Visualización de álgebra lineal",
                    },
                ],
            },
            {
                "id": "machine-learning",
                "name": "Machine Learning",
                "description": "Regresión, clasificación, clustering, scikit-learn",
                "difficulty": "advanced",
                "estimated_weeks": 5,
                "status": "planned",
                "icon": "bi-robot",
                "order": 2,
                "resources": [
                    {
                        "type": "course",
                        "name": "Coursera - ML by Andrew Ng",
                        "url": "https://www.coursera.org/learn/machine-learning",
                        "is_free": True,
                        "description": "El curso más clásico de ML",
                    },
                    {
                        "type": "course",
                        "name": "Kaggle - Intro to ML",
                        "url": "https://www.kaggle.com/learn/intro-to-machine-learning",
                        "is_free": True,
                        "description": "ML práctico con Kaggle",
                    },
                    {
                        "type": "tool",
                        "name": "Scikit-learn Docs",
                        "url": "https://scikit-learn.org/stable/tutorial/",
                        "is_free": True,
                        "description": "Tutorial oficial de scikit-learn",
                    },
                ],
            },
            {
                "id": "deep-learning",
                "name": "Deep Learning",
                "description": "Redes neuronales, CNN, RNN, TensorFlow, PyTorch",
                "difficulty": "advanced",
                "estimated_weeks": 5,
                "status": "planned",
                "icon": "bi-cpu",
                "order": 3,
                "resources": [
                    {
                        "type": "course",
                        "name": "fast.ai - Practical Deep Learning",
                        "url": "https://course.fast.ai/",
                        "is_free": True,
                        "description": "Curso práctico de deep learning",
                    },
                    {
                        "type": "course",
                        "name": "Deep Learning Specialization",
                        "url": "https://www.coursera.org/specializations/deep-learning",
                        "is_free": True,
                        "description": "5 cursos de deep learning",
                    },
                    {
                        "type": "tool",
                        "name": "PyTorch Tutorials",
                        "url": "https://pytorch.org/tutorials/",
                        "is_free": True,
                        "description": "Tutoriales oficiales de PyTorch",
                    },
                ],
            },
            {
                "id": "nlp",
                "name": "Procesamiento de Lenguaje Natural",
                "description": "NLP, transformers, BERT, GPT, Hugging Face",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-chat-dots",
                "order": 4,
                "resources": [
                    {
                        "type": "course",
                        "name": "Hugging Face NLP Course",
                        "url": "https://huggingface.co/learn/nlp-course",
                        "is_free": True,
                        "description": "Curso oficial de Hugging Face",
                    },
                    {
                        "type": "article",
                        "name": "Jay Alammar - Illustrated Transformer",
                        "url": "https://jalammar.github.io/",
                        "is_free": True,
                        "description": "Transformers explicados visualmente",
                    },
                    {
                        "type": "tool",
                        "name": "Hugging Face Hub",
                        "url": "https://huggingface.co/models",
                        "is_free": True,
                        "description": "Miles de modelos pre-entrenados",
                    },
                ],
            },
            {
                "id": "proyectos-ia",
                "name": "Proyectos de IA",
                "description": "Aplicar IA a problemas reales, portafolio, kaggle competitions",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-rocket-takeoff",
                "order": 5,
                "resources": [
                    {
                        "type": "practice",
                        "name": "Kaggle Competitions",
                        "url": "https://www.kaggle.com/competitions",
                        "is_free": True,
                        "description": "Competencias de ML reales",
                    },
                    {
                        "type": "practice",
                        "name": "Papers with Code",
                        "url": "https://paperswithcode.com/",
                        "is_free": True,
                        "description": "Paper + código reproducible",
                    },
                    {
                        "type": "article",
                        "name": "KDnuggets",
                        "url": "https://www.kdnuggets.com/",
                        "is_free": True,
                        "description": "Artículos de ciencia de datos e IA",
                    },
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════
    # CLOUD / DEVOPS
    # ═══════════════════════════════════════════════════════════════
    {
        "goal_id": "Cloud",
        "title": "Ruta DevOps y Cloud",
        "subtitle": "Infraestructura moderna y despliegue continuo",
        "color": "#0ea5e9",
        "nodes": [
            {
                "id": "linux-fundamentals",
                "name": "Linux Fundamentals",
                "description": "Comandos, shell scripting, permisos, gestión de procesos",
                "difficulty": "basic",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-terminal",
                "order": 0,
                "resources": [
                    {
                        "type": "course",
                        "name": "Linux Journey",
                        "url": "https://linuxjourney.com/",
                        "is_free": True,
                        "description": "Aprende Linux paso a paso",
                    },
                    {
                        "type": "practice",
                        "name": "OverTheWire - Bandit",
                        "url": "https://overthewire.org/wargames/bandit/",
                        "is_free": True,
                        "description": "Aprende Linux jugando",
                    },
                    {
                        "type": "article",
                        "name": "Linux Commands Cheat Sheet",
                        "url": "https://www.linuxtrainingacademy.com/linux-commands-cheat-sheet/",
                        "is_free": True,
                        "description": "Referencia rápida de comandos",
                    },
                ],
            },
            {
                "id": "git-github",
                "name": "Git & GitHub",
                "description": "Control de versiones, branching, workflows, pull requests",
                "difficulty": "basic",
                "estimated_weeks": 1,
                "status": "planned",
                "icon": "bi-git",
                "order": 1,
                "resources": [
                    {
                        "type": "course",
                        "name": "Git Official Tutorial",
                        "url": "https://git-scm.com/doc",
                        "is_free": True,
                        "description": "Documentación oficial de Git",
                    },
                    {
                        "type": "practice",
                        "name": "Learn Git Branching",
                        "url": "https://learngitbranching.js.org/",
                        "is_free": True,
                        "description": "Aprende git de forma interactiva",
                    },
                    {
                        "type": "article",
                        "name": "GitHub Skills",
                        "url": "https://skills.github.com/",
                        "is_free": True,
                        "description": "Cursos interactivos de GitHub",
                    },
                ],
            },
            {
                "id": "docker-containers",
                "name": "Docker & Containers",
                "description": "Imágenes, Dockerfile, Compose, redes, volúmenes",
                "difficulty": "intermediate",
                "estimated_weeks": 3,
                "status": "planned",
                "icon": "bi-box",
                "order": 2,
                "resources": [
                    {
                        "type": "course",
                        "name": "Docker Official Get Started",
                        "url": "https://docs.docker.com/get-started/",
                        "is_free": True,
                        "description": "Tutorial oficial de Docker",
                    },
                    {
                        "type": "practice",
                        "name": "Play with Docker",
                        "url": "https://labs.play-with-docker.com/",
                        "is_free": True,
                        "description": "Practica Docker en el navegador",
                    },
                    {
                        "type": "article",
                        "name": "Docker Curriculum",
                        "url": "https://docker-curriculum.com/",
                        "is_free": True,
                        "description": "Guía completa para principiantes",
                    },
                ],
            },
            {
                "id": "kubernetes",
                "name": "Kubernetes",
                "description": "Pods, services, deployments, Helm, ingress",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-cloud",
                "order": 3,
                "resources": [
                    {
                        "type": "course",
                        "name": "Kubernetes Official Tutorials",
                        "url": "https://kubernetes.io/docs/tutorials/",
                        "is_free": True,
                        "description": "Tutoriales oficiales de K8s",
                    },
                    {
                        "type": "practice",
                        "name": "KillerCoda K8s",
                        "url": "https://killercoda.com/playgrounds/scenario/kubernetes",
                        "is_free": True,
                        "description": "Laboratorios interactivos de K8s",
                    },
                    {
                        "type": "tool",
                        "name": "minikube",
                        "url": "https://minikube.sigs.k8s.io/docs/start/",
                        "is_free": True,
                        "description": "Kubernetes local para desarrollo",
                    },
                ],
            },
            {
                "id": "ci-cd",
                "name": "CI/CD Pipelines",
                "description": "GitHub Actions, GitLab CI, Jenkins, pipelines automatizados",
                "difficulty": "intermediate",
                "estimated_weeks": 3,
                "status": "planned",
                "icon": "bi-arrow-repeat",
                "order": 4,
                "resources": [
                    {
                        "type": "tool",
                        "name": "GitHub Actions Docs",
                        "url": "https://docs.github.com/en/actions",
                        "is_free": True,
                        "description": "Documentación oficial de GitHub Actions",
                    },
                    {
                        "type": "course",
                        "name": "GitHub Learning Lab",
                        "url": "https://lab.github.com/",
                        "is_free": True,
                        "description": "Cursos interactivos de CI/CD",
                    },
                    {
                        "type": "article",
                        "name": "GitLab CI/CD Docs",
                        "url": "https://docs.gitlab.com/ee/ci/",
                        "is_free": True,
                        "description": "Documentación de GitLab CI",
                    },
                ],
            },
            {
                "id": "infrastructure-as-code",
                "name": "Infrastructure as Code",
                "description": "Terraform, Ansible, CloudFormation, gestión declarativa",
                "difficulty": "advanced",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-gear",
                "order": 5,
                "resources": [
                    {
                        "type": "course",
                        "name": "Terraform Official Tutorials",
                        "url": "https://developer.hashicorp.com/terraform/tutorials",
                        "is_free": True,
                        "description": "Tutoriales oficiales de Terraform",
                    },
                    {
                        "type": "course",
                        "name": "Ansible Getting Started",
                        "url": "https://docs.ansible.com/ansible/latest/getting_started/index.html",
                        "is_free": True,
                        "description": "Inicio rápido con Ansible",
                    },
                    {
                        "type": "practice",
                        "name": "Terraform Cloud Free",
                        "url": "https://app.terraform.io/public/signup",
                        "is_free": True,
                        "description": "Terraform Cloud con tier gratuito",
                    },
                ],
            },
            {
                "id": "monitoring",
                "name": "Monitoring & Observability",
                "description": "Prometheus, Grafana, ELK Stack, métricas y alertas",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-graph-up",
                "order": 6,
                "resources": [
                    {
                        "type": "tool",
                        "name": "Grafana Play",
                        "url": "https://play.grafana.org/",
                        "is_free": True,
                        "description": "Experimenta con Grafana online",
                    },
                    {
                        "type": "course",
                        "name": "Prometheus Getting Started",
                        "url": "https://prometheus.io/docs/prometheus/latest/getting_started/",
                        "is_free": True,
                        "description": "Tutorial oficial de Prometheus",
                    },
                    {
                        "type": "article",
                        "name": "ELK Stack Guide",
                        "url": "https://www.elastic.co/guide/en/elastic-stack/current/index.html",
                        "is_free": True,
                        "description": "Documentación del ELK Stack",
                    },
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════
    # FRONTEND
    # ═══════════════════════════════════════════════════════════════
    {
        "goal_id": "Frontend",
        "title": "Ruta Desarrollo Frontend",
        "subtitle": "Construye interfaces modernas y responsivas",
        "color": "#06b6d4",
        "nodes": [
            {
                "id": "html-css",
                "name": "HTML & CSS",
                "description": "Semántica, Flexbox, CSS Grid, responsive design",
                "difficulty": "basic",
                "estimated_weeks": 3,
                "status": "planned",
                "icon": "bi-palette",
                "order": 0,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - Responsive Web Design",
                        "url": "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
                        "is_free": True,
                        "description": "Diseño web responsivo desde cero",
                    },
                    {
                        "type": "article",
                        "name": "MDN - CSS Basics",
                        "url": "https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps",
                        "is_free": True,
                        "description": "Fundamentos de CSS en MDN",
                    },
                    {
                        "type": "practice",
                        "name": "CSS Battle",
                        "url": "https://cssbattle.dev/",
                        "is_free": True,
                        "description": "Practica CSS con retos visuales",
                    },
                ],
            },
            {
                "id": "javascript-avanzado",
                "name": "JavaScript Avanzado",
                "description": "ES6+, async/await, closures, prototypes, DOM",
                "difficulty": "intermediate",
                "estimated_weeks": 4,
                "status": "planned",
                "icon": "bi-filetype-js",
                "order": 1,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - JS Algorithms",
                        "url": "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/",
                        "is_free": True,
                        "description": "JS moderno con ejercicios",
                    },
                    {
                        "type": "article",
                        "name": "JavaScript.info",
                        "url": "https://javascript.info/",
                        "is_free": True,
                        "description": "El libro de JavaScript moderno",
                    },
                    {
                        "type": "practice",
                        "name": "CodeWars",
                        "url": "https://www.codewars.com/",
                        "is_free": True,
                        "description": "Kata de JavaScript para practicar",
                    },
                ],
            },
            {
                "id": "typescript",
                "name": "TypeScript",
                "description": "Tipos, interfaces, genéricos, utilidades, config",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-file-code",
                "order": 2,
                "resources": [
                    {
                        "type": "course",
                        "name": "TypeScript Official Handbook",
                        "url": "https://www.typescriptlang.org/docs/handbook/",
                        "is_free": True,
                        "description": "Manual oficial de TypeScript",
                    },
                    {
                        "type": "practice",
                        "name": "Type Challenges",
                        "url": "https://github.com/type-challenges/type-challenges",
                        "is_free": True,
                        "description": "Retos de tipos de TypeScript",
                    },
                    {
                        "type": "article",
                        "name": "TypeScript Exercises",
                        "url": "https://typescript-exercises.github.io/",
                        "is_free": True,
                        "description": "Ejercicios interactivos de TypeScript",
                    },
                ],
            },
            {
                "id": "framework-moderno",
                "name": "Framework Moderno (React/Vue/Angular)",
                "description": "Componentes, hooks/signals, routing, state management",
                "difficulty": "intermediate",
                "estimated_weeks": 5,
                "status": "planned",
                "icon": "bi-app-indicator",
                "order": 3,
                "resources": [
                    {
                        "type": "course",
                        "name": "React Official Tutorial",
                        "url": "https://react.dev/learn",
                        "is_free": True,
                        "description": "Tutorial oficial de React",
                    },
                    {
                        "type": "course",
                        "name": "Vue.js Official Guide",
                        "url": "https://vuejs.org/guide/introduction.html",
                        "is_free": True,
                        "description": "Guía oficial de Vue.js",
                    },
                    {
                        "type": "course",
                        "name": "Angular Tour of Heroes",
                        "url": "https://angular.dev/tutorial",
                        "is_free": True,
                        "description": "Tutorial oficial de Angular",
                    },
                ],
            },
            {
                "id": "state-management",
                "name": "State Management",
                "description": "Redux Toolkit, Pinia, Context API, Zustand",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-stack",
                "order": 4,
                "resources": [
                    {
                        "type": "course",
                        "name": "Redux Essentials",
                        "url": "https://redux.js.org/tutorials/essentials/part-1-overview-concepts",
                        "is_free": True,
                        "description": "Tutorial oficial de Redux",
                    },
                    {
                        "type": "article",
                        "name": "Pinia Documentation",
                        "url": "https://pinia.vuejs.org/",
                        "is_free": True,
                        "description": "State management para Vue",
                    },
                    {
                        "type": "practice",
                        "name": "Zustand Examples",
                        "url": "https://github.com/pmndrs/zustand#readme",
                        "is_free": True,
                        "description": "Ejemplos de Zustand para React",
                    },
                ],
            },
            {
                "id": "testing-frontend",
                "name": "Testing & Debugging",
                "description": "Unit tests, integration tests, e2e, devtools",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-bug",
                "order": 5,
                "resources": [
                    {
                        "type": "course",
                        "name": "Vitest Getting Started",
                        "url": "https://vitest.dev/guide/",
                        "is_free": True,
                        "description": "Testing rápido con Vitest",
                    },
                    {
                        "type": "tool",
                        "name": "Playwright Docs",
                        "url": "https://playwright.dev/docs/intro",
                        "is_free": True,
                        "description": "Testing end-to-end con Playwright",
                    },
                    {
                        "type": "article",
                        "name": "Testing Library Docs",
                        "url": "https://testing-library.com/docs/",
                        "is_free": True,
                        "description": "Principios de testing de componentes",
                    },
                ],
            },
            {
                "id": "performance-seo",
                "name": "Performance & SEO",
                "description": "Bundle optimization, lazy loading, Core Web Vitals, SEO",
                "difficulty": "advanced",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-lightning",
                "order": 6,
                "resources": [
                    {
                        "type": "tool",
                        "name": "PageSpeed Insights",
                        "url": "https://pagespeed.web.dev/",
                        "is_free": True,
                        "description": "Mide la performance de tus apps",
                    },
                    {
                        "type": "article",
                        "name": "Web.dev Learn",
                        "url": "https://web.dev/learn",
                        "is_free": True,
                        "description": "Guías de performance de Google",
                    },
                    {
                        "type": "tool",
                        "name": "Lighthouse",
                        "url": "https://developer.chrome.com/docs/lighthouse/overview",
                        "is_free": True,
                        "description": "Auditoría de performance y SEO",
                    },
                ],
            },
        ],
    },
    # ═══════════════════════════════════════════════════════════════
    # GENERAL
    # ═══════════════════════════════════════════════════════════════
    {
        "goal_id": "General",
        "title": "Ruta General Tech",
        "subtitle": "Fundamentos sólidos para cualquier área de tecnología",
        "color": "#64748b",
        "nodes": [
            {
                "id": "logica-programacion",
                "name": "Lógica de Programación",
                "description": "Pensamiento algorítmico, pseudocódigo, flujo",
                "difficulty": "basic",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-diagram-2",
                "order": 0,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - Problem Solving",
                        "url": "https://www.freecodecamp.org/learn/responsive-web-design/",
                        "is_free": True,
                        "description": "Resolución de problemas",
                    },
                    {
                        "type": "practice",
                        "name": "Scratch",
                        "url": "https://scratch.mit.edu/",
                        "is_free": True,
                        "description": "Aprende lógica visualmente",
                    },
                    {
                        "type": "article",
                        "name": "Think Like a Programmer",
                        "url": "https://opensourcesoftwarewithvrdev.medium.com/",
                        "is_free": True,
                        "description": "Consejos para pensar como programador",
                    },
                ],
            },
            {
                "id": "fundamentos-web",
                "name": "Fundamentos Web",
                "description": "Cómo funciona internet, HTTP, DNS, browsers",
                "difficulty": "basic",
                "estimated_weeks": 1,
                "status": "planned",
                "icon": "bi-globe",
                "order": 1,
                "resources": [
                    {
                        "type": "course",
                        "name": "freeCodeCamp - How the Internet Works",
                        "url": "https://www.freecodecamp.org/",
                        "is_free": True,
                        "description": "Fundamentos de internet",
                    },
                    {
                        "type": "article",
                        "name": "How the Internet Works",
                        "url": "https://computer.howstuffworks.com/internet.htm",
                        "is_free": True,
                        "description": "Cómo funciona internet",
                    },
                    {
                        "type": "tool",
                        "name": "MDN Web Docs",
                        "url": "https://developer.mozilla.org/",
                        "is_free": True,
                        "description": "La referencia definitiva de web",
                    },
                ],
            },
            {
                "id": "git-basico",
                "name": "Git Básico",
                "description": "Commits, branches, merge, pull requests",
                "difficulty": "basic",
                "estimated_weeks": 1,
                "status": "planned",
                "icon": "bi-git",
                "order": 2,
                "resources": [
                    {
                        "type": "course",
                        "name": "Git Official Tutorial",
                        "url": "https://git-scm.com/doc",
                        "is_free": True,
                        "description": "Documentación oficial",
                    },
                    {
                        "type": "practice",
                        "name": "Learn Git Branching",
                        "url": "https://learngitbranching.js.org/",
                        "is_free": True,
                        "description": "Aprende git interactivamente",
                    },
                    {
                        "type": "article",
                        "name": "GitHub Skills",
                        "url": "https://skills.github.com/",
                        "is_free": True,
                        "description": "Cursos interactivos",
                    },
                ],
            },
            {
                "id": "bases-datos-conceptos",
                "name": "Conceptos de Bases de Datos",
                "description": "SQL básico, normalización, diagramas ER",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-database",
                "order": 3,
                "resources": [
                    {
                        "type": "course",
                        "name": "Khan Academy - SQL",
                        "url": "https://www.khanacademy.org/computing/computer-science/sql",
                        "is_free": True,
                        "description": "SQL interactivo",
                    },
                    {
                        "type": "practice",
                        "name": "SQLZoo",
                        "url": "https://sqlzoo.net/",
                        "is_free": True,
                        "description": "Practica SQL online",
                    },
                    {
                        "type": "practice",
                        "name": "DB Fiddle",
                        "url": "https://www.db-fiddle.com/",
                        "is_free": True,
                        "description": "Experimenta con bases de datos",
                    },
                ],
            },
            {
                "id": "apis-conceptos",
                "name": "APIs y Servicios Web",
                "description": "REST, JSON, autenticación básica, HTTP methods",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-cloud-arrow-up",
                "order": 4,
                "resources": [
                    {
                        "type": "article",
                        "name": "MDN - HTTP Overview",
                        "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
                        "is_free": True,
                        "description": "Overview de HTTP",
                    },
                    {
                        "type": "tool",
                        "name": "JSONPlaceholder",
                        "url": "https://jsonplaceholder.typicode.com/",
                        "is_free": True,
                        "description": "API fake para practicar",
                    },
                    {
                        "type": "tool",
                        "name": "Postman",
                        "url": "https://www.postman.com/",
                        "is_free": True,
                        "description": "Cliente HTTP para probar APIs",
                    },
                ],
            },
            {
                "id": "seguridad-basica",
                "name": "Seguridad Básica",
                "description": "OWASP Top 10, HTTPS, autenticación, buenas prácticas",
                "difficulty": "intermediate",
                "estimated_weeks": 2,
                "status": "planned",
                "icon": "bi-shield-check",
                "order": 5,
                "resources": [
                    {
                        "type": "article",
                        "name": "OWASP Top 10",
                        "url": "https://owasp.org/Top10/",
                        "is_free": True,
                        "description": "Los 10 riesgos más comunes",
                    },
                    {
                        "type": "course",
                        "name": "PortSwigger Web Security",
                        "url": "https://portswigger.net/web-security",
                        "is_free": True,
                        "description": "Aprende seguridad web",
                    },
                    {
                        "type": "article",
                        "name": "Auth0 Learning",
                        "url": "https://auth0.com/learn",
                        "is_free": True,
                        "description": "Aprende sobre autenticación",
                    },
                ],
            },
        ],
    },
]


async def seed():
    await connect_to_mongo()
    db = get_database()
    col = db["learning_paths"]

    # Upsert each path (update if goal_id exists, insert if not)
    for path in SEED_DATA:
        now = datetime.utcnow()
        nodes = path["nodes"]
        await col.update_one(
            {"goal_id": path["goal_id"]},
            {
                "$set": {
                    "title": path["title"],
                    "subtitle": path["subtitle"],
                    "color": path["color"],
                    "nodes": nodes,
                    "updated_at": now,
                },
                "$setOnInsert": {
                    "created_at": now,
                },
            },
            upsert=True,
        )
        print(f"  ✓ {path['goal_id']}: {len(nodes)} nodes seeded")

    await close_mongo_connection()
    print(f"\n✅ Seeded {len(SEED_DATA)} learning paths into MongoDB.")


if __name__ == "__main__":
    import asyncio

    asyncio.run(seed())
